### ISSUE TITLE
Unidirectional links on Piccadilly line in the Heathrow area -- minor bug?

### ISSUE THREAD

**Issue by gwselke** [manwar/Map-Tube-London#4]
The London Tube map (the official one) seems to me to indicate that the Piccadilly line, at the Heathrow end, goes from Hatton Cross to Heathrow Terminal 4 and on to Heathrow Terminal 2&3 (but not the other way round, so: unidirectional), and thence to Hatton Cross. (As opposed to the branch from Hatton Cross through Terminal 2&3 to Terminal 5, which seems to be "normal", i.e., bidirectional.)
In this reading I would expect 
`map-tube --map=London --start="Heathrow Terminal 4" --end="Hatton Cross" --preferred`
to yield
`Heathrow Terminal 4 (Piccadilly), Heathrow Terminals 2 & 3 (Piccadilly), Hatton Cross (Piccadilly)`
and not
`Heathrow Terminal 4 (Piccadilly), Hatton Cross (Piccadilly)`

**Comment by manwar** [comment]
@gwselke once again, thank you for your continuous support and encouragement.
I have released the patch: Map::Tube v3.88 and Map::Tube::London v1.40 but for some reason, it is not showing up on MetaCPAN.
I have reported this to the Team MetaCPAN.
Please give it a try from the source (GitHub), if you can't get it from CPAN directly.

**Comment by gwselke** [comment]
Hi Mohammad -

It seems to be tricky. I think the connection between Heathrow Terminals 2 & 3 and Hatton Cross should be bidirectional.
map-tube... --start="Hatton Cross" --end="Heathrow Terminals 2 & 3"
currently sends you through Heathrow Terminal 4.
Consulting tfl.gov.uk/plan-a-journey, however, yields a direct (non-stop) cobbection between the two named stations.
From my understanding, only the two connections involving Terminal 4 are unidirectional. 
-- 
\Gisbert


-------- Ursprüngliche Nachricht --------
Von: Mohammad Sajid Anwar ***@***.***>
Gesendet: 17. Dezember 2024 13:52:00 MEZ
An: manwar/Map-Tube-London ***@***.***>
CC: gwselke ***@***.***>, Mention ***@***.***>
Betreff: Re: [manwar/Map-Tube-London] Unidirectional links on Piccadilly line in the Heathrow area -- minor bug? (Issue #4)

@gwselke once again, thank you for your continuous support and encouragement.
I have released the patch: Map::Tube v3.88 and Map::Tube::London v1.40 but for some reason, it is not showing up on MetaCPAN.
I have reported this to the Team MetaCPAN.
Please give it a try from the source (GitHub), if you can't get it from CPAN directly.

**Comment by manwar** [comment]
@gwselke Yes, you are right. 
I have released patch just now. Map::Tube::London v1.41.

**Comment by gwselke** [comment]
Perfect now -- thank you for your fast responses, Mohammad!
